title: Finite & Learnable
description: A corner to share my understanding of the various mathematical topics in a fun way (not always).  
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# hide the GitHub box
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
